### ISSUE TITLE
Add option to add a link to images slides

### ISSUE THREAD

**Issue by awenro** [madeyourday/rocksolid-slider#21]
We might try to find a way to add a link to image slides since this is often requested: https://community.contao.org/de/showthread.php?55049-Slider-RockSlider-oder-besser-anderer

The current option to add a content element seams to be to hard to understand.

**Comment by ausi** [comment]
Support for slideable links was added in cc6946afb3fa81345dd00dd99ebab3a6d4fdefb2, for the rest see madeyourday/contao-rocksolid-slider#16
