### ISSUE TITLE
Add name search for slider list

### ISSUE THREAD

**Issue by aschempp** [madeyourday/rocksolid-slider#37]
```php
$GLOBALS['TL_DCA']['tl_rocksolid_slider']['fields']['name']['search'] = true;
```

😎

**Comment by ausi** [comment]
Thanks for the suggestion, but the correct place for this issue would be in [madeyourday/contao-rocksolid-slider](https://github.com/madeyourday/contao-rocksolid-slider) as it is regarding the Contao integration, not the JS slider itself.

**Comment by aschempp** [comment]
see https://github.com/madeyourday/contao-rocksolid-slider/issues/30
