### ISSUE TITLE
Fehler mit moo_mediabox/bei Endlosschleife/bei geraden Elementen

### ISSUE THREAD

**Issue by lennier83** [madeyourday/rocksolid-slider#42]
Hallo liebe Entwickler.
Ich hab gesehen, dass wenn ich beim Slider gerade Element-Anzahlen (2/4/6 ...) drin habe und die Endlosschleife, dann funktioniert die moo_mediabox nicht korrekt. 
Egal ob Bild-Slider oder Inhalt-Slider.
Z.B. bei zwei Elementen: das erste Bild funktioniert, beim zweiten Bild geht das Bild nicht in der Lightbox auf, sondern im Fenster.
Das ist ein Fehler ausschließlich via mediabox.
Siehe http://srp-devserver.de/geo/index.php/startseite.html (drittes Bild).
Konnte das, wo das jetzt aufgekommen ist, bei allen Projekten reproduzieren (habe sonst immer die colorbox).

Ungerade Elemente (1/3/5...) funktionieren perfekt mit der Endlosschleife.
Kann man was dazu sagen?

Contao =<3.5.27
Slider 1.6.2

Beste Grüße und Danke

**Comment by ausi** [comment]
Duplicate: madeyourday/contao-rocksolid-slider#45
